name: Build and Deploy Fullstack App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current files (debug)
        run: |
          pwd
          ls -la
          ls -la Backend
          ls -la Frontend

      - name: DockerHub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest

      - name: Setup SSH key for deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest
            docker stop fullstack-app || true
            docker rm fullstack-app || true
            docker run -d --name fullstack-app -p 80:3001 ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest
EOF
