- name: Debug: List files in current directory
  run: |
    pwd
    ls -la

- name: Debug: Show Dockerfile content
  run: cat Dockerfile

- name: Build and Push Docker Image
  run: |
    docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest .
    docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest
