name: Simple Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check working directory
        run: |
          pwd
          ls -la
